"""
Core data models for Harness
"""

from datetime import datetime
from enum import Enum
from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field


class TaskStatus(str, Enum):
    PENDING = "pending"
    PLANNING = "planning"
    GENERATING = "generating"
    EVALUATING = "evaluating"
    COMPLETED = "completed"
    FAILED = "failed"


class Step(BaseModel):
    """A single step in the execution plan"""

    id: str
    description: str
    status: TaskStatus = TaskStatus.PENDING
    dependencies: List[str] = []
    output: Optional[str] = None
    error: Optional[str] = None
    started_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None


class Task(BaseModel):
    """A task to be executed"""

    id: str = Field(default_factory=lambda: f"task_{datetime.now().strftime('%Y%m%d_%H%M%S')}")
    description: str
    status: TaskStatus = TaskStatus.PENDING
    steps: List[Step] = []
    context: Dict[str, Any] = {}
    created_at: datetime = Field(default_factory=datetime.now)
    updated_at: datetime = Field(default_factory=datetime.now)


class Plan(BaseModel):
    """Execution plan generated by Planner"""

    task_id: str
    steps: List[Step]
    estimated_complexity: float = 0.5  # 0-1 scale
    is_complex: bool = False
    rationale: str = ""


class Issue(BaseModel):
    """An issue found by Evaluator"""

    severity: str  # "critical", "major", "minor"
    description: str
    location: Optional[str] = None  # Where the issue was found
    suggestion: Optional[str] = None  # How to fix


class Evaluation(BaseModel):
    """Evaluation result from Evaluator"""

    passed: bool
    score: float  # 0-1
    issues: List[Issue] = []
    strengths: List[str] = []
    summary: str = ""
    evaluated_at: datetime = Field(default_factory=datetime.now)


class Skill(BaseModel):
    """An extracted skill"""

    id: str = Field(default_factory=lambda: f"skill_{datetime.now().strftime('%Y%m%d_%H%M%S')}")
    name: str
    description: str  # Used for triggering
    steps: List[str]  # Standard procedure
    checkpoints: List[str] = []  # Key checkpoints
    examples: List[str] = []  # Success cases
    tags: List[str] = []
    created_at: datetime = Field(default_factory=datetime.now)
    source_task_id: Optional[str] = None


class GoldenRule(BaseModel):
    """A golden rule/constraint"""

    id: str
    content: str
    category: str  # "global", "domain", "format"
    priority: int = 1  # 1-5, higher is more important
    created_at: datetime = Field(default_factory=datetime.now)
